// Generated by gencpp from file foxbot/robot_SetVacuumRequest.msg
// DO NOT EDIT!


#ifndef FOXBOT_MESSAGE_ROBOT_SETVACUUMREQUEST_H
#define FOXBOT_MESSAGE_ROBOT_SETVACUUMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace foxbot
{
template <class ContainerAllocator>
struct robot_SetVacuumRequest_
{
  typedef robot_SetVacuumRequest_<ContainerAllocator> Type;

  robot_SetVacuumRequest_()
    : vacuum(0)  {
    }
  robot_SetVacuumRequest_(const ContainerAllocator& _alloc)
    : vacuum(0)  {
    }



   typedef int64_t _vacuum_type;
  _vacuum_type vacuum;




  typedef boost::shared_ptr< ::foxbot::robot_SetVacuumRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::foxbot::robot_SetVacuumRequest_<ContainerAllocator> const> ConstPtr;

}; // struct robot_SetVacuumRequest_

typedef ::foxbot::robot_SetVacuumRequest_<std::allocator<void> > robot_SetVacuumRequest;

typedef boost::shared_ptr< ::foxbot::robot_SetVacuumRequest > robot_SetVacuumRequestPtr;
typedef boost::shared_ptr< ::foxbot::robot_SetVacuumRequest const> robot_SetVacuumRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::foxbot::robot_SetVacuumRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::foxbot::robot_SetVacuumRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace foxbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'foxbot': ['/home/biomed/feroze_ws/src/foxbot/msg'], 'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::foxbot::robot_SetVacuumRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::foxbot::robot_SetVacuumRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::foxbot::robot_SetVacuumRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::foxbot::robot_SetVacuumRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::foxbot::robot_SetVacuumRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::foxbot::robot_SetVacuumRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::foxbot::robot_SetVacuumRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ee7741d1da0c9620d77add3d4997c2d";
  }

  static const char* value(const ::foxbot::robot_SetVacuumRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ee7741d1da0c962ULL;
  static const uint64_t static_value2 = 0x0d77add3d4997c2dULL;
};

template<class ContainerAllocator>
struct DataType< ::foxbot::robot_SetVacuumRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "foxbot/robot_SetVacuumRequest";
  }

  static const char* value(const ::foxbot::robot_SetVacuumRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::foxbot::robot_SetVacuumRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
int64 vacuum\n\
";
  }

  static const char* value(const ::foxbot::robot_SetVacuumRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::foxbot::robot_SetVacuumRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vacuum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct robot_SetVacuumRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::foxbot::robot_SetVacuumRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::foxbot::robot_SetVacuumRequest_<ContainerAllocator>& v)
  {
    s << indent << "vacuum: ";
    Printer<int64_t>::stream(s, indent + "  ", v.vacuum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FOXBOT_MESSAGE_ROBOT_SETVACUUMREQUEST_H
