// Generated by gencpp from file foxbot/robot_SetJoints.msg
// DO NOT EDIT!


#ifndef FOXBOT_MESSAGE_ROBOT_SETJOINTS_H
#define FOXBOT_MESSAGE_ROBOT_SETJOINTS_H

#include <ros/service_traits.h>


#include <foxbot/robot_SetJointsRequest.h>
#include <foxbot/robot_SetJointsResponse.h>


namespace foxbot
{

struct robot_SetJoints
{

typedef robot_SetJointsRequest Request;
typedef robot_SetJointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_SetJoints
} // namespace foxbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::foxbot::robot_SetJoints > {
  static const char* value()
  {
    return "446aa11c6398bf454927125e45f82131";
  }

  static const char* value(const ::foxbot::robot_SetJoints&) { return value(); }
};

template<>
struct DataType< ::foxbot::robot_SetJoints > {
  static const char* value()
  {
    return "foxbot/robot_SetJoints";
  }

  static const char* value(const ::foxbot::robot_SetJoints&) { return value(); }
};


// service_traits::MD5Sum< ::foxbot::robot_SetJointsRequest> should match 
// service_traits::MD5Sum< ::foxbot::robot_SetJoints > 
template<>
struct MD5Sum< ::foxbot::robot_SetJointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::foxbot::robot_SetJoints >::value();
  }
  static const char* value(const ::foxbot::robot_SetJointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::foxbot::robot_SetJointsRequest> should match 
// service_traits::DataType< ::foxbot::robot_SetJoints > 
template<>
struct DataType< ::foxbot::robot_SetJointsRequest>
{
  static const char* value()
  {
    return DataType< ::foxbot::robot_SetJoints >::value();
  }
  static const char* value(const ::foxbot::robot_SetJointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::foxbot::robot_SetJointsResponse> should match 
// service_traits::MD5Sum< ::foxbot::robot_SetJoints > 
template<>
struct MD5Sum< ::foxbot::robot_SetJointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::foxbot::robot_SetJoints >::value();
  }
  static const char* value(const ::foxbot::robot_SetJointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::foxbot::robot_SetJointsResponse> should match 
// service_traits::DataType< ::foxbot::robot_SetJoints > 
template<>
struct DataType< ::foxbot::robot_SetJointsResponse>
{
  static const char* value()
  {
    return DataType< ::foxbot::robot_SetJoints >::value();
  }
  static const char* value(const ::foxbot::robot_SetJointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FOXBOT_MESSAGE_ROBOT_SETJOINTS_H
