// Generated by gencpp from file foxbot/robot_SetTrackDist.msg
// DO NOT EDIT!


#ifndef FOXBOT_MESSAGE_ROBOT_SETTRACKDIST_H
#define FOXBOT_MESSAGE_ROBOT_SETTRACKDIST_H

#include <ros/service_traits.h>


#include <foxbot/robot_SetTrackDistRequest.h>
#include <foxbot/robot_SetTrackDistResponse.h>


namespace foxbot
{

struct robot_SetTrackDist
{

typedef robot_SetTrackDistRequest Request;
typedef robot_SetTrackDistResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_SetTrackDist
} // namespace foxbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::foxbot::robot_SetTrackDist > {
  static const char* value()
  {
    return "eb267eb8369d9c3a686d934285ba7a11";
  }

  static const char* value(const ::foxbot::robot_SetTrackDist&) { return value(); }
};

template<>
struct DataType< ::foxbot::robot_SetTrackDist > {
  static const char* value()
  {
    return "foxbot/robot_SetTrackDist";
  }

  static const char* value(const ::foxbot::robot_SetTrackDist&) { return value(); }
};


// service_traits::MD5Sum< ::foxbot::robot_SetTrackDistRequest> should match 
// service_traits::MD5Sum< ::foxbot::robot_SetTrackDist > 
template<>
struct MD5Sum< ::foxbot::robot_SetTrackDistRequest>
{
  static const char* value()
  {
    return MD5Sum< ::foxbot::robot_SetTrackDist >::value();
  }
  static const char* value(const ::foxbot::robot_SetTrackDistRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::foxbot::robot_SetTrackDistRequest> should match 
// service_traits::DataType< ::foxbot::robot_SetTrackDist > 
template<>
struct DataType< ::foxbot::robot_SetTrackDistRequest>
{
  static const char* value()
  {
    return DataType< ::foxbot::robot_SetTrackDist >::value();
  }
  static const char* value(const ::foxbot::robot_SetTrackDistRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::foxbot::robot_SetTrackDistResponse> should match 
// service_traits::MD5Sum< ::foxbot::robot_SetTrackDist > 
template<>
struct MD5Sum< ::foxbot::robot_SetTrackDistResponse>
{
  static const char* value()
  {
    return MD5Sum< ::foxbot::robot_SetTrackDist >::value();
  }
  static const char* value(const ::foxbot::robot_SetTrackDistResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::foxbot::robot_SetTrackDistResponse> should match 
// service_traits::DataType< ::foxbot::robot_SetTrackDist > 
template<>
struct DataType< ::foxbot::robot_SetTrackDistResponse>
{
  static const char* value()
  {
    return DataType< ::foxbot::robot_SetTrackDist >::value();
  }
  static const char* value(const ::foxbot::robot_SetTrackDistResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FOXBOT_MESSAGE_ROBOT_SETTRACKDIST_H
