// Generated by gencpp from file foxbot/robot_StopTracking.msg
// DO NOT EDIT!


#ifndef FOXBOT_MESSAGE_ROBOT_STOPTRACKING_H
#define FOXBOT_MESSAGE_ROBOT_STOPTRACKING_H

#include <ros/service_traits.h>


#include <foxbot/robot_StopTrackingRequest.h>
#include <foxbot/robot_StopTrackingResponse.h>


namespace foxbot
{

struct robot_StopTracking
{

typedef robot_StopTrackingRequest Request;
typedef robot_StopTrackingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_StopTracking
} // namespace foxbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::foxbot::robot_StopTracking > {
  static const char* value()
  {
    return "1e32786be6359fbbb6259aee4f579d10";
  }

  static const char* value(const ::foxbot::robot_StopTracking&) { return value(); }
};

template<>
struct DataType< ::foxbot::robot_StopTracking > {
  static const char* value()
  {
    return "foxbot/robot_StopTracking";
  }

  static const char* value(const ::foxbot::robot_StopTracking&) { return value(); }
};


// service_traits::MD5Sum< ::foxbot::robot_StopTrackingRequest> should match 
// service_traits::MD5Sum< ::foxbot::robot_StopTracking > 
template<>
struct MD5Sum< ::foxbot::robot_StopTrackingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::foxbot::robot_StopTracking >::value();
  }
  static const char* value(const ::foxbot::robot_StopTrackingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::foxbot::robot_StopTrackingRequest> should match 
// service_traits::DataType< ::foxbot::robot_StopTracking > 
template<>
struct DataType< ::foxbot::robot_StopTrackingRequest>
{
  static const char* value()
  {
    return DataType< ::foxbot::robot_StopTracking >::value();
  }
  static const char* value(const ::foxbot::robot_StopTrackingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::foxbot::robot_StopTrackingResponse> should match 
// service_traits::MD5Sum< ::foxbot::robot_StopTracking > 
template<>
struct MD5Sum< ::foxbot::robot_StopTrackingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::foxbot::robot_StopTracking >::value();
  }
  static const char* value(const ::foxbot::robot_StopTrackingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::foxbot::robot_StopTrackingResponse> should match 
// service_traits::DataType< ::foxbot::robot_StopTracking > 
template<>
struct DataType< ::foxbot::robot_StopTrackingResponse>
{
  static const char* value()
  {
    return DataType< ::foxbot::robot_StopTracking >::value();
  }
  static const char* value(const ::foxbot::robot_StopTrackingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FOXBOT_MESSAGE_ROBOT_STOPTRACKING_H
