// Generated by gencpp from file foxbot/robot_JogCartesian.msg
// DO NOT EDIT!


#ifndef FOXBOT_MESSAGE_ROBOT_JOGCARTESIAN_H
#define FOXBOT_MESSAGE_ROBOT_JOGCARTESIAN_H

#include <ros/service_traits.h>


#include <foxbot/robot_JogCartesianRequest.h>
#include <foxbot/robot_JogCartesianResponse.h>


namespace foxbot
{

struct robot_JogCartesian
{

typedef robot_JogCartesianRequest Request;
typedef robot_JogCartesianResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_JogCartesian
} // namespace foxbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::foxbot::robot_JogCartesian > {
  static const char* value()
  {
    return "6827eacd06482159aec120b550d48bb7";
  }

  static const char* value(const ::foxbot::robot_JogCartesian&) { return value(); }
};

template<>
struct DataType< ::foxbot::robot_JogCartesian > {
  static const char* value()
  {
    return "foxbot/robot_JogCartesian";
  }

  static const char* value(const ::foxbot::robot_JogCartesian&) { return value(); }
};


// service_traits::MD5Sum< ::foxbot::robot_JogCartesianRequest> should match 
// service_traits::MD5Sum< ::foxbot::robot_JogCartesian > 
template<>
struct MD5Sum< ::foxbot::robot_JogCartesianRequest>
{
  static const char* value()
  {
    return MD5Sum< ::foxbot::robot_JogCartesian >::value();
  }
  static const char* value(const ::foxbot::robot_JogCartesianRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::foxbot::robot_JogCartesianRequest> should match 
// service_traits::DataType< ::foxbot::robot_JogCartesian > 
template<>
struct DataType< ::foxbot::robot_JogCartesianRequest>
{
  static const char* value()
  {
    return DataType< ::foxbot::robot_JogCartesian >::value();
  }
  static const char* value(const ::foxbot::robot_JogCartesianRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::foxbot::robot_JogCartesianResponse> should match 
// service_traits::MD5Sum< ::foxbot::robot_JogCartesian > 
template<>
struct MD5Sum< ::foxbot::robot_JogCartesianResponse>
{
  static const char* value()
  {
    return MD5Sum< ::foxbot::robot_JogCartesian >::value();
  }
  static const char* value(const ::foxbot::robot_JogCartesianResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::foxbot::robot_JogCartesianResponse> should match 
// service_traits::DataType< ::foxbot::robot_JogCartesian > 
template<>
struct DataType< ::foxbot::robot_JogCartesianResponse>
{
  static const char* value()
  {
    return DataType< ::foxbot::robot_JogCartesian >::value();
  }
  static const char* value(const ::foxbot::robot_JogCartesianResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FOXBOT_MESSAGE_ROBOT_JOGCARTESIAN_H
