// Generated by gencpp from file foxbot/robot_Ping.msg
// DO NOT EDIT!


#ifndef FOXBOT_MESSAGE_ROBOT_PING_H
#define FOXBOT_MESSAGE_ROBOT_PING_H

#include <ros/service_traits.h>


#include <foxbot/robot_PingRequest.h>
#include <foxbot/robot_PingResponse.h>


namespace foxbot
{

struct robot_Ping
{

typedef robot_PingRequest Request;
typedef robot_PingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_Ping
} // namespace foxbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::foxbot::robot_Ping > {
  static const char* value()
  {
    return "1e32786be6359fbbb6259aee4f579d10";
  }

  static const char* value(const ::foxbot::robot_Ping&) { return value(); }
};

template<>
struct DataType< ::foxbot::robot_Ping > {
  static const char* value()
  {
    return "foxbot/robot_Ping";
  }

  static const char* value(const ::foxbot::robot_Ping&) { return value(); }
};


// service_traits::MD5Sum< ::foxbot::robot_PingRequest> should match 
// service_traits::MD5Sum< ::foxbot::robot_Ping > 
template<>
struct MD5Sum< ::foxbot::robot_PingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::foxbot::robot_Ping >::value();
  }
  static const char* value(const ::foxbot::robot_PingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::foxbot::robot_PingRequest> should match 
// service_traits::DataType< ::foxbot::robot_Ping > 
template<>
struct DataType< ::foxbot::robot_PingRequest>
{
  static const char* value()
  {
    return DataType< ::foxbot::robot_Ping >::value();
  }
  static const char* value(const ::foxbot::robot_PingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::foxbot::robot_PingResponse> should match 
// service_traits::MD5Sum< ::foxbot::robot_Ping > 
template<>
struct MD5Sum< ::foxbot::robot_PingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::foxbot::robot_Ping >::value();
  }
  static const char* value(const ::foxbot::robot_PingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::foxbot::robot_PingResponse> should match 
// service_traits::DataType< ::foxbot::robot_Ping > 
template<>
struct DataType< ::foxbot::robot_PingResponse>
{
  static const char* value()
  {
    return DataType< ::foxbot::robot_Ping >::value();
  }
  static const char* value(const ::foxbot::robot_PingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FOXBOT_MESSAGE_ROBOT_PING_H
