// Generated by gencpp from file foxbot/robot_IsMoving.msg
// DO NOT EDIT!


#ifndef FOXBOT_MESSAGE_ROBOT_ISMOVING_H
#define FOXBOT_MESSAGE_ROBOT_ISMOVING_H

#include <ros/service_traits.h>


#include <foxbot/robot_IsMovingRequest.h>
#include <foxbot/robot_IsMovingResponse.h>


namespace foxbot
{

struct robot_IsMoving
{

typedef robot_IsMovingRequest Request;
typedef robot_IsMovingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_IsMoving
} // namespace foxbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::foxbot::robot_IsMoving > {
  static const char* value()
  {
    return "6a8e4a0e30cc934246f28f5db62a1332";
  }

  static const char* value(const ::foxbot::robot_IsMoving&) { return value(); }
};

template<>
struct DataType< ::foxbot::robot_IsMoving > {
  static const char* value()
  {
    return "foxbot/robot_IsMoving";
  }

  static const char* value(const ::foxbot::robot_IsMoving&) { return value(); }
};


// service_traits::MD5Sum< ::foxbot::robot_IsMovingRequest> should match 
// service_traits::MD5Sum< ::foxbot::robot_IsMoving > 
template<>
struct MD5Sum< ::foxbot::robot_IsMovingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::foxbot::robot_IsMoving >::value();
  }
  static const char* value(const ::foxbot::robot_IsMovingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::foxbot::robot_IsMovingRequest> should match 
// service_traits::DataType< ::foxbot::robot_IsMoving > 
template<>
struct DataType< ::foxbot::robot_IsMovingRequest>
{
  static const char* value()
  {
    return DataType< ::foxbot::robot_IsMoving >::value();
  }
  static const char* value(const ::foxbot::robot_IsMovingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::foxbot::robot_IsMovingResponse> should match 
// service_traits::MD5Sum< ::foxbot::robot_IsMoving > 
template<>
struct MD5Sum< ::foxbot::robot_IsMovingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::foxbot::robot_IsMoving >::value();
  }
  static const char* value(const ::foxbot::robot_IsMovingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::foxbot::robot_IsMovingResponse> should match 
// service_traits::DataType< ::foxbot::robot_IsMoving > 
template<>
struct DataType< ::foxbot::robot_IsMovingResponse>
{
  static const char* value()
  {
    return DataType< ::foxbot::robot_IsMoving >::value();
  }
  static const char* value(const ::foxbot::robot_IsMovingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FOXBOT_MESSAGE_ROBOT_ISMOVING_H
