// Generated by gencpp from file foxbot/robot_SetTrackingRequest.msg
// DO NOT EDIT!


#ifndef FOXBOT_MESSAGE_ROBOT_SETTRACKINGREQUEST_H
#define FOXBOT_MESSAGE_ROBOT_SETTRACKINGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace foxbot
{
template <class ContainerAllocator>
struct robot_SetTrackingRequest_
{
  typedef robot_SetTrackingRequest_<ContainerAllocator> Type;

  robot_SetTrackingRequest_()
    : vx(0.0)
    , vy(0.0)
    , vz(0.0)  {
    }
  robot_SetTrackingRequest_(const ContainerAllocator& _alloc)
    : vx(0.0)
    , vy(0.0)
    , vz(0.0)  {
    }



   typedef double _vx_type;
  _vx_type vx;

   typedef double _vy_type;
  _vy_type vy;

   typedef double _vz_type;
  _vz_type vz;




  typedef boost::shared_ptr< ::foxbot::robot_SetTrackingRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::foxbot::robot_SetTrackingRequest_<ContainerAllocator> const> ConstPtr;

}; // struct robot_SetTrackingRequest_

typedef ::foxbot::robot_SetTrackingRequest_<std::allocator<void> > robot_SetTrackingRequest;

typedef boost::shared_ptr< ::foxbot::robot_SetTrackingRequest > robot_SetTrackingRequestPtr;
typedef boost::shared_ptr< ::foxbot::robot_SetTrackingRequest const> robot_SetTrackingRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::foxbot::robot_SetTrackingRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::foxbot::robot_SetTrackingRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace foxbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'foxbot': ['/home/biomed/feroze_ws/src/foxbot/msg'], 'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::foxbot::robot_SetTrackingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::foxbot::robot_SetTrackingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::foxbot::robot_SetTrackingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::foxbot::robot_SetTrackingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::foxbot::robot_SetTrackingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::foxbot::robot_SetTrackingRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::foxbot::robot_SetTrackingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ffb367ff390f5e01cb55c0c75927c19a";
  }

  static const char* value(const ::foxbot::robot_SetTrackingRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xffb367ff390f5e01ULL;
  static const uint64_t static_value2 = 0xcb55c0c75927c19aULL;
};

template<class ContainerAllocator>
struct DataType< ::foxbot::robot_SetTrackingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "foxbot/robot_SetTrackingRequest";
  }

  static const char* value(const ::foxbot::robot_SetTrackingRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::foxbot::robot_SetTrackingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
float64 vx\n\
float64 vy\n\
float64 vz\n\
";
  }

  static const char* value(const ::foxbot::robot_SetTrackingRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::foxbot::robot_SetTrackingRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vx);
      stream.next(m.vy);
      stream.next(m.vz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct robot_SetTrackingRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::foxbot::robot_SetTrackingRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::foxbot::robot_SetTrackingRequest_<ContainerAllocator>& v)
  {
    s << indent << "vx: ";
    Printer<double>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<double>::stream(s, indent + "  ", v.vy);
    s << indent << "vz: ";
    Printer<double>::stream(s, indent + "  ", v.vz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FOXBOT_MESSAGE_ROBOT_SETTRACKINGREQUEST_H
