// Generated by gencpp from file foxbot/robot_GetFKRequest.msg
// DO NOT EDIT!


#ifndef FOXBOT_MESSAGE_ROBOT_GETFKREQUEST_H
#define FOXBOT_MESSAGE_ROBOT_GETFKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace foxbot
{
template <class ContainerAllocator>
struct robot_GetFKRequest_
{
  typedef robot_GetFKRequest_<ContainerAllocator> Type;

  robot_GetFKRequest_()
    : j1(0.0)
    , j2(0.0)
    , j3(0.0)
    , j4(0.0)
    , j5(0.0)
    , j6(0.0)  {
    }
  robot_GetFKRequest_(const ContainerAllocator& _alloc)
    : j1(0.0)
    , j2(0.0)
    , j3(0.0)
    , j4(0.0)
    , j5(0.0)
    , j6(0.0)  {
    }



   typedef double _j1_type;
  _j1_type j1;

   typedef double _j2_type;
  _j2_type j2;

   typedef double _j3_type;
  _j3_type j3;

   typedef double _j4_type;
  _j4_type j4;

   typedef double _j5_type;
  _j5_type j5;

   typedef double _j6_type;
  _j6_type j6;




  typedef boost::shared_ptr< ::foxbot::robot_GetFKRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::foxbot::robot_GetFKRequest_<ContainerAllocator> const> ConstPtr;

}; // struct robot_GetFKRequest_

typedef ::foxbot::robot_GetFKRequest_<std::allocator<void> > robot_GetFKRequest;

typedef boost::shared_ptr< ::foxbot::robot_GetFKRequest > robot_GetFKRequestPtr;
typedef boost::shared_ptr< ::foxbot::robot_GetFKRequest const> robot_GetFKRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::foxbot::robot_GetFKRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::foxbot::robot_GetFKRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace foxbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/jade/share/std_msgs/cmake/../msg'], 'foxbot': ['/home/biomed/feroze_ws/src/foxbot/msg'], 'geometry_msgs': ['/opt/ros/jade/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::foxbot::robot_GetFKRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::foxbot::robot_GetFKRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::foxbot::robot_GetFKRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::foxbot::robot_GetFKRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::foxbot::robot_GetFKRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::foxbot::robot_GetFKRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::foxbot::robot_GetFKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "30e3b3187560ea4f8505d287c27ca8d4";
  }

  static const char* value(const ::foxbot::robot_GetFKRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x30e3b3187560ea4fULL;
  static const uint64_t static_value2 = 0x8505d287c27ca8d4ULL;
};

template<class ContainerAllocator>
struct DataType< ::foxbot::robot_GetFKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "foxbot/robot_GetFKRequest";
  }

  static const char* value(const ::foxbot::robot_GetFKRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::foxbot::robot_GetFKRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
float64 j1\n\
float64 j2\n\
float64 j3\n\
float64 j4\n\
float64 j5\n\
float64 j6\n\
\n\
";
  }

  static const char* value(const ::foxbot::robot_GetFKRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::foxbot::robot_GetFKRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.j1);
      stream.next(m.j2);
      stream.next(m.j3);
      stream.next(m.j4);
      stream.next(m.j5);
      stream.next(m.j6);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct robot_GetFKRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::foxbot::robot_GetFKRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::foxbot::robot_GetFKRequest_<ContainerAllocator>& v)
  {
    s << indent << "j1: ";
    Printer<double>::stream(s, indent + "  ", v.j1);
    s << indent << "j2: ";
    Printer<double>::stream(s, indent + "  ", v.j2);
    s << indent << "j3: ";
    Printer<double>::stream(s, indent + "  ", v.j3);
    s << indent << "j4: ";
    Printer<double>::stream(s, indent + "  ", v.j4);
    s << indent << "j5: ";
    Printer<double>::stream(s, indent + "  ", v.j5);
    s << indent << "j6: ";
    Printer<double>::stream(s, indent + "  ", v.j6);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FOXBOT_MESSAGE_ROBOT_GETFKREQUEST_H
