// Generated by gencpp from file foxbot/robot_SetZone.msg
// DO NOT EDIT!


#ifndef FOXBOT_MESSAGE_ROBOT_SETZONE_H
#define FOXBOT_MESSAGE_ROBOT_SETZONE_H

#include <ros/service_traits.h>


#include <foxbot/robot_SetZoneRequest.h>
#include <foxbot/robot_SetZoneResponse.h>


namespace foxbot
{

struct robot_SetZone
{

typedef robot_SetZoneRequest Request;
typedef robot_SetZoneResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_SetZone
} // namespace foxbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::foxbot::robot_SetZone > {
  static const char* value()
  {
    return "9a8139bbede588258d8a8cdc808e7b88";
  }

  static const char* value(const ::foxbot::robot_SetZone&) { return value(); }
};

template<>
struct DataType< ::foxbot::robot_SetZone > {
  static const char* value()
  {
    return "foxbot/robot_SetZone";
  }

  static const char* value(const ::foxbot::robot_SetZone&) { return value(); }
};


// service_traits::MD5Sum< ::foxbot::robot_SetZoneRequest> should match 
// service_traits::MD5Sum< ::foxbot::robot_SetZone > 
template<>
struct MD5Sum< ::foxbot::robot_SetZoneRequest>
{
  static const char* value()
  {
    return MD5Sum< ::foxbot::robot_SetZone >::value();
  }
  static const char* value(const ::foxbot::robot_SetZoneRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::foxbot::robot_SetZoneRequest> should match 
// service_traits::DataType< ::foxbot::robot_SetZone > 
template<>
struct DataType< ::foxbot::robot_SetZoneRequest>
{
  static const char* value()
  {
    return DataType< ::foxbot::robot_SetZone >::value();
  }
  static const char* value(const ::foxbot::robot_SetZoneRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::foxbot::robot_SetZoneResponse> should match 
// service_traits::MD5Sum< ::foxbot::robot_SetZone > 
template<>
struct MD5Sum< ::foxbot::robot_SetZoneResponse>
{
  static const char* value()
  {
    return MD5Sum< ::foxbot::robot_SetZone >::value();
  }
  static const char* value(const ::foxbot::robot_SetZoneResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::foxbot::robot_SetZoneResponse> should match 
// service_traits::DataType< ::foxbot::robot_SetZone > 
template<>
struct DataType< ::foxbot::robot_SetZoneResponse>
{
  static const char* value()
  {
    return DataType< ::foxbot::robot_SetZone >::value();
  }
  static const char* value(const ::foxbot::robot_SetZoneResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FOXBOT_MESSAGE_ROBOT_SETZONE_H
