// Generated by gencpp from file foxbot/robot_SetCartesian.msg
// DO NOT EDIT!


#ifndef FOXBOT_MESSAGE_ROBOT_SETCARTESIAN_H
#define FOXBOT_MESSAGE_ROBOT_SETCARTESIAN_H

#include <ros/service_traits.h>


#include <foxbot/robot_SetCartesianRequest.h>
#include <foxbot/robot_SetCartesianResponse.h>


namespace foxbot
{

struct robot_SetCartesian
{

typedef robot_SetCartesianRequest Request;
typedef robot_SetCartesianResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_SetCartesian
} // namespace foxbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::foxbot::robot_SetCartesian > {
  static const char* value()
  {
    return "48105d2c73aad743181a15ec5fd389ae";
  }

  static const char* value(const ::foxbot::robot_SetCartesian&) { return value(); }
};

template<>
struct DataType< ::foxbot::robot_SetCartesian > {
  static const char* value()
  {
    return "foxbot/robot_SetCartesian";
  }

  static const char* value(const ::foxbot::robot_SetCartesian&) { return value(); }
};


// service_traits::MD5Sum< ::foxbot::robot_SetCartesianRequest> should match 
// service_traits::MD5Sum< ::foxbot::robot_SetCartesian > 
template<>
struct MD5Sum< ::foxbot::robot_SetCartesianRequest>
{
  static const char* value()
  {
    return MD5Sum< ::foxbot::robot_SetCartesian >::value();
  }
  static const char* value(const ::foxbot::robot_SetCartesianRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::foxbot::robot_SetCartesianRequest> should match 
// service_traits::DataType< ::foxbot::robot_SetCartesian > 
template<>
struct DataType< ::foxbot::robot_SetCartesianRequest>
{
  static const char* value()
  {
    return DataType< ::foxbot::robot_SetCartesian >::value();
  }
  static const char* value(const ::foxbot::robot_SetCartesianRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::foxbot::robot_SetCartesianResponse> should match 
// service_traits::MD5Sum< ::foxbot::robot_SetCartesian > 
template<>
struct MD5Sum< ::foxbot::robot_SetCartesianResponse>
{
  static const char* value()
  {
    return MD5Sum< ::foxbot::robot_SetCartesian >::value();
  }
  static const char* value(const ::foxbot::robot_SetCartesianResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::foxbot::robot_SetCartesianResponse> should match 
// service_traits::DataType< ::foxbot::robot_SetCartesian > 
template<>
struct DataType< ::foxbot::robot_SetCartesianResponse>
{
  static const char* value()
  {
    return DataType< ::foxbot::robot_SetCartesian >::value();
  }
  static const char* value(const ::foxbot::robot_SetCartesianResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FOXBOT_MESSAGE_ROBOT_SETCARTESIAN_H
