// Generated by gencpp from file foxbot/robot_SetTracking.msg
// DO NOT EDIT!


#ifndef FOXBOT_MESSAGE_ROBOT_SETTRACKING_H
#define FOXBOT_MESSAGE_ROBOT_SETTRACKING_H

#include <ros/service_traits.h>


#include <foxbot/robot_SetTrackingRequest.h>
#include <foxbot/robot_SetTrackingResponse.h>


namespace foxbot
{

struct robot_SetTracking
{

typedef robot_SetTrackingRequest Request;
typedef robot_SetTrackingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_SetTracking
} // namespace foxbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::foxbot::robot_SetTracking > {
  static const char* value()
  {
    return "1f549db0b4ab74a589a50385066d187f";
  }

  static const char* value(const ::foxbot::robot_SetTracking&) { return value(); }
};

template<>
struct DataType< ::foxbot::robot_SetTracking > {
  static const char* value()
  {
    return "foxbot/robot_SetTracking";
  }

  static const char* value(const ::foxbot::robot_SetTracking&) { return value(); }
};


// service_traits::MD5Sum< ::foxbot::robot_SetTrackingRequest> should match 
// service_traits::MD5Sum< ::foxbot::robot_SetTracking > 
template<>
struct MD5Sum< ::foxbot::robot_SetTrackingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::foxbot::robot_SetTracking >::value();
  }
  static const char* value(const ::foxbot::robot_SetTrackingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::foxbot::robot_SetTrackingRequest> should match 
// service_traits::DataType< ::foxbot::robot_SetTracking > 
template<>
struct DataType< ::foxbot::robot_SetTrackingRequest>
{
  static const char* value()
  {
    return DataType< ::foxbot::robot_SetTracking >::value();
  }
  static const char* value(const ::foxbot::robot_SetTrackingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::foxbot::robot_SetTrackingResponse> should match 
// service_traits::MD5Sum< ::foxbot::robot_SetTracking > 
template<>
struct MD5Sum< ::foxbot::robot_SetTrackingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::foxbot::robot_SetTracking >::value();
  }
  static const char* value(const ::foxbot::robot_SetTrackingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::foxbot::robot_SetTrackingResponse> should match 
// service_traits::DataType< ::foxbot::robot_SetTracking > 
template<>
struct DataType< ::foxbot::robot_SetTrackingResponse>
{
  static const char* value()
  {
    return DataType< ::foxbot::robot_SetTracking >::value();
  }
  static const char* value(const ::foxbot::robot_SetTrackingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FOXBOT_MESSAGE_ROBOT_SETTRACKING_H
