// Generated by gencpp from file foxbot/robot_SetVacuum.msg
// DO NOT EDIT!


#ifndef FOXBOT_MESSAGE_ROBOT_SETVACUUM_H
#define FOXBOT_MESSAGE_ROBOT_SETVACUUM_H

#include <ros/service_traits.h>


#include <foxbot/robot_SetVacuumRequest.h>
#include <foxbot/robot_SetVacuumResponse.h>


namespace foxbot
{

struct robot_SetVacuum
{

typedef robot_SetVacuumRequest Request;
typedef robot_SetVacuumResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_SetVacuum
} // namespace foxbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::foxbot::robot_SetVacuum > {
  static const char* value()
  {
    return "bc2b2a4e5d5d788edc958a62cf84dc1f";
  }

  static const char* value(const ::foxbot::robot_SetVacuum&) { return value(); }
};

template<>
struct DataType< ::foxbot::robot_SetVacuum > {
  static const char* value()
  {
    return "foxbot/robot_SetVacuum";
  }

  static const char* value(const ::foxbot::robot_SetVacuum&) { return value(); }
};


// service_traits::MD5Sum< ::foxbot::robot_SetVacuumRequest> should match 
// service_traits::MD5Sum< ::foxbot::robot_SetVacuum > 
template<>
struct MD5Sum< ::foxbot::robot_SetVacuumRequest>
{
  static const char* value()
  {
    return MD5Sum< ::foxbot::robot_SetVacuum >::value();
  }
  static const char* value(const ::foxbot::robot_SetVacuumRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::foxbot::robot_SetVacuumRequest> should match 
// service_traits::DataType< ::foxbot::robot_SetVacuum > 
template<>
struct DataType< ::foxbot::robot_SetVacuumRequest>
{
  static const char* value()
  {
    return DataType< ::foxbot::robot_SetVacuum >::value();
  }
  static const char* value(const ::foxbot::robot_SetVacuumRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::foxbot::robot_SetVacuumResponse> should match 
// service_traits::MD5Sum< ::foxbot::robot_SetVacuum > 
template<>
struct MD5Sum< ::foxbot::robot_SetVacuumResponse>
{
  static const char* value()
  {
    return MD5Sum< ::foxbot::robot_SetVacuum >::value();
  }
  static const char* value(const ::foxbot::robot_SetVacuumResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::foxbot::robot_SetVacuumResponse> should match 
// service_traits::DataType< ::foxbot::robot_SetVacuum > 
template<>
struct DataType< ::foxbot::robot_SetVacuumResponse>
{
  static const char* value()
  {
    return DataType< ::foxbot::robot_SetVacuum >::value();
  }
  static const char* value(const ::foxbot::robot_SetVacuumResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FOXBOT_MESSAGE_ROBOT_SETVACUUM_H
