// Generated by gencpp from file foxbot/robot_Stop.msg
// DO NOT EDIT!


#ifndef FOXBOT_MESSAGE_ROBOT_STOP_H
#define FOXBOT_MESSAGE_ROBOT_STOP_H

#include <ros/service_traits.h>


#include <foxbot/robot_StopRequest.h>
#include <foxbot/robot_StopResponse.h>


namespace foxbot
{

struct robot_Stop
{

typedef robot_StopRequest Request;
typedef robot_StopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_Stop
} // namespace foxbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::foxbot::robot_Stop > {
  static const char* value()
  {
    return "1e32786be6359fbbb6259aee4f579d10";
  }

  static const char* value(const ::foxbot::robot_Stop&) { return value(); }
};

template<>
struct DataType< ::foxbot::robot_Stop > {
  static const char* value()
  {
    return "foxbot/robot_Stop";
  }

  static const char* value(const ::foxbot::robot_Stop&) { return value(); }
};


// service_traits::MD5Sum< ::foxbot::robot_StopRequest> should match 
// service_traits::MD5Sum< ::foxbot::robot_Stop > 
template<>
struct MD5Sum< ::foxbot::robot_StopRequest>
{
  static const char* value()
  {
    return MD5Sum< ::foxbot::robot_Stop >::value();
  }
  static const char* value(const ::foxbot::robot_StopRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::foxbot::robot_StopRequest> should match 
// service_traits::DataType< ::foxbot::robot_Stop > 
template<>
struct DataType< ::foxbot::robot_StopRequest>
{
  static const char* value()
  {
    return DataType< ::foxbot::robot_Stop >::value();
  }
  static const char* value(const ::foxbot::robot_StopRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::foxbot::robot_StopResponse> should match 
// service_traits::MD5Sum< ::foxbot::robot_Stop > 
template<>
struct MD5Sum< ::foxbot::robot_StopResponse>
{
  static const char* value()
  {
    return MD5Sum< ::foxbot::robot_Stop >::value();
  }
  static const char* value(const ::foxbot::robot_StopResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::foxbot::robot_StopResponse> should match 
// service_traits::DataType< ::foxbot::robot_Stop > 
template<>
struct DataType< ::foxbot::robot_StopResponse>
{
  static const char* value()
  {
    return DataType< ::foxbot::robot_Stop >::value();
  }
  static const char* value(const ::foxbot::robot_StopResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FOXBOT_MESSAGE_ROBOT_STOP_H
