// Generated by gencpp from file foxbot/robot_SetSpeedRequest.msg
// DO NOT EDIT!


#ifndef FOXBOT_MESSAGE_ROBOT_SETSPEEDREQUEST_H
#define FOXBOT_MESSAGE_ROBOT_SETSPEEDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace foxbot
{
template <class ContainerAllocator>
struct robot_SetSpeedRequest_
{
  typedef robot_SetSpeedRequest_<ContainerAllocator> Type;

  robot_SetSpeedRequest_()
    : tcp(0.0)
    , ori(0.0)  {
    }
  robot_SetSpeedRequest_(const ContainerAllocator& _alloc)
    : tcp(0.0)
    , ori(0.0)  {
  (void)_alloc;
    }



   typedef double _tcp_type;
  _tcp_type tcp;

   typedef double _ori_type;
  _ori_type ori;




  typedef boost::shared_ptr< ::foxbot::robot_SetSpeedRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::foxbot::robot_SetSpeedRequest_<ContainerAllocator> const> ConstPtr;

}; // struct robot_SetSpeedRequest_

typedef ::foxbot::robot_SetSpeedRequest_<std::allocator<void> > robot_SetSpeedRequest;

typedef boost::shared_ptr< ::foxbot::robot_SetSpeedRequest > robot_SetSpeedRequestPtr;
typedef boost::shared_ptr< ::foxbot::robot_SetSpeedRequest const> robot_SetSpeedRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::foxbot::robot_SetSpeedRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::foxbot::robot_SetSpeedRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace foxbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'foxbot': ['/home/biomed/feroze_biorobotics/feroze_ws/src/foxbot/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::foxbot::robot_SetSpeedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::foxbot::robot_SetSpeedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::foxbot::robot_SetSpeedRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::foxbot::robot_SetSpeedRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::foxbot::robot_SetSpeedRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::foxbot::robot_SetSpeedRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::foxbot::robot_SetSpeedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9f0ff1193cfb3499a7608d4091f40f93";
  }

  static const char* value(const ::foxbot::robot_SetSpeedRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9f0ff1193cfb3499ULL;
  static const uint64_t static_value2 = 0xa7608d4091f40f93ULL;
};

template<class ContainerAllocator>
struct DataType< ::foxbot::robot_SetSpeedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "foxbot/robot_SetSpeedRequest";
  }

  static const char* value(const ::foxbot::robot_SetSpeedRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::foxbot::robot_SetSpeedRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
float64 tcp\n\
float64 ori\n\
";
  }

  static const char* value(const ::foxbot::robot_SetSpeedRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::foxbot::robot_SetSpeedRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tcp);
      stream.next(m.ori);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_SetSpeedRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::foxbot::robot_SetSpeedRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::foxbot::robot_SetSpeedRequest_<ContainerAllocator>& v)
  {
    s << indent << "tcp: ";
    Printer<double>::stream(s, indent + "  ", v.tcp);
    s << indent << "ori: ";
    Printer<double>::stream(s, indent + "  ", v.ori);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FOXBOT_MESSAGE_ROBOT_SETSPEEDREQUEST_H
