// Generated by gencpp from file foxbot/robot_SetCartesianJ.msg
// DO NOT EDIT!


#ifndef FOXBOT_MESSAGE_ROBOT_SETCARTESIANJ_H
#define FOXBOT_MESSAGE_ROBOT_SETCARTESIANJ_H

#include <ros/service_traits.h>


#include <foxbot/robot_SetCartesianJRequest.h>
#include <foxbot/robot_SetCartesianJResponse.h>


namespace foxbot
{

struct robot_SetCartesianJ
{

typedef robot_SetCartesianJRequest Request;
typedef robot_SetCartesianJResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_SetCartesianJ
} // namespace foxbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::foxbot::robot_SetCartesianJ > {
  static const char* value()
  {
    return "13716a3f1e232bc5200a276031ef97c2";
  }

  static const char* value(const ::foxbot::robot_SetCartesianJ&) { return value(); }
};

template<>
struct DataType< ::foxbot::robot_SetCartesianJ > {
  static const char* value()
  {
    return "foxbot/robot_SetCartesianJ";
  }

  static const char* value(const ::foxbot::robot_SetCartesianJ&) { return value(); }
};


// service_traits::MD5Sum< ::foxbot::robot_SetCartesianJRequest> should match 
// service_traits::MD5Sum< ::foxbot::robot_SetCartesianJ > 
template<>
struct MD5Sum< ::foxbot::robot_SetCartesianJRequest>
{
  static const char* value()
  {
    return MD5Sum< ::foxbot::robot_SetCartesianJ >::value();
  }
  static const char* value(const ::foxbot::robot_SetCartesianJRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::foxbot::robot_SetCartesianJRequest> should match 
// service_traits::DataType< ::foxbot::robot_SetCartesianJ > 
template<>
struct DataType< ::foxbot::robot_SetCartesianJRequest>
{
  static const char* value()
  {
    return DataType< ::foxbot::robot_SetCartesianJ >::value();
  }
  static const char* value(const ::foxbot::robot_SetCartesianJRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::foxbot::robot_SetCartesianJResponse> should match 
// service_traits::MD5Sum< ::foxbot::robot_SetCartesianJ > 
template<>
struct MD5Sum< ::foxbot::robot_SetCartesianJResponse>
{
  static const char* value()
  {
    return MD5Sum< ::foxbot::robot_SetCartesianJ >::value();
  }
  static const char* value(const ::foxbot::robot_SetCartesianJResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::foxbot::robot_SetCartesianJResponse> should match 
// service_traits::DataType< ::foxbot::robot_SetCartesianJ > 
template<>
struct DataType< ::foxbot::robot_SetCartesianJResponse>
{
  static const char* value()
  {
    return DataType< ::foxbot::robot_SetCartesianJ >::value();
  }
  static const char* value(const ::foxbot::robot_SetCartesianJResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FOXBOT_MESSAGE_ROBOT_SETCARTESIANJ_H
