// Generated by gencpp from file foxbot/robot_GetFK.msg
// DO NOT EDIT!


#ifndef FOXBOT_MESSAGE_ROBOT_GETFK_H
#define FOXBOT_MESSAGE_ROBOT_GETFK_H

#include <ros/service_traits.h>


#include <foxbot/robot_GetFKRequest.h>
#include <foxbot/robot_GetFKResponse.h>


namespace foxbot
{

struct robot_GetFK
{

typedef robot_GetFKRequest Request;
typedef robot_GetFKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_GetFK
} // namespace foxbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::foxbot::robot_GetFK > {
  static const char* value()
  {
    return "c6deda797d8a6e552534be5c1a9e2f8d";
  }

  static const char* value(const ::foxbot::robot_GetFK&) { return value(); }
};

template<>
struct DataType< ::foxbot::robot_GetFK > {
  static const char* value()
  {
    return "foxbot/robot_GetFK";
  }

  static const char* value(const ::foxbot::robot_GetFK&) { return value(); }
};


// service_traits::MD5Sum< ::foxbot::robot_GetFKRequest> should match 
// service_traits::MD5Sum< ::foxbot::robot_GetFK > 
template<>
struct MD5Sum< ::foxbot::robot_GetFKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::foxbot::robot_GetFK >::value();
  }
  static const char* value(const ::foxbot::robot_GetFKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::foxbot::robot_GetFKRequest> should match 
// service_traits::DataType< ::foxbot::robot_GetFK > 
template<>
struct DataType< ::foxbot::robot_GetFKRequest>
{
  static const char* value()
  {
    return DataType< ::foxbot::robot_GetFK >::value();
  }
  static const char* value(const ::foxbot::robot_GetFKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::foxbot::robot_GetFKResponse> should match 
// service_traits::MD5Sum< ::foxbot::robot_GetFK > 
template<>
struct MD5Sum< ::foxbot::robot_GetFKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::foxbot::robot_GetFK >::value();
  }
  static const char* value(const ::foxbot::robot_GetFKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::foxbot::robot_GetFKResponse> should match 
// service_traits::DataType< ::foxbot::robot_GetFK > 
template<>
struct DataType< ::foxbot::robot_GetFKResponse>
{
  static const char* value()
  {
    return DataType< ::foxbot::robot_GetFK >::value();
  }
  static const char* value(const ::foxbot::robot_GetFKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FOXBOT_MESSAGE_ROBOT_GETFK_H
