// Generated by gencpp from file foxbot/robot_SetComm.msg
// DO NOT EDIT!


#ifndef FOXBOT_MESSAGE_ROBOT_SETCOMM_H
#define FOXBOT_MESSAGE_ROBOT_SETCOMM_H

#include <ros/service_traits.h>


#include <foxbot/robot_SetCommRequest.h>
#include <foxbot/robot_SetCommResponse.h>


namespace foxbot
{

struct robot_SetComm
{

typedef robot_SetCommRequest Request;
typedef robot_SetCommResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_SetComm
} // namespace foxbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::foxbot::robot_SetComm > {
  static const char* value()
  {
    return "9a8139bbede588258d8a8cdc808e7b88";
  }

  static const char* value(const ::foxbot::robot_SetComm&) { return value(); }
};

template<>
struct DataType< ::foxbot::robot_SetComm > {
  static const char* value()
  {
    return "foxbot/robot_SetComm";
  }

  static const char* value(const ::foxbot::robot_SetComm&) { return value(); }
};


// service_traits::MD5Sum< ::foxbot::robot_SetCommRequest> should match 
// service_traits::MD5Sum< ::foxbot::robot_SetComm > 
template<>
struct MD5Sum< ::foxbot::robot_SetCommRequest>
{
  static const char* value()
  {
    return MD5Sum< ::foxbot::robot_SetComm >::value();
  }
  static const char* value(const ::foxbot::robot_SetCommRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::foxbot::robot_SetCommRequest> should match 
// service_traits::DataType< ::foxbot::robot_SetComm > 
template<>
struct DataType< ::foxbot::robot_SetCommRequest>
{
  static const char* value()
  {
    return DataType< ::foxbot::robot_SetComm >::value();
  }
  static const char* value(const ::foxbot::robot_SetCommRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::foxbot::robot_SetCommResponse> should match 
// service_traits::MD5Sum< ::foxbot::robot_SetComm > 
template<>
struct MD5Sum< ::foxbot::robot_SetCommResponse>
{
  static const char* value()
  {
    return MD5Sum< ::foxbot::robot_SetComm >::value();
  }
  static const char* value(const ::foxbot::robot_SetCommResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::foxbot::robot_SetCommResponse> should match 
// service_traits::DataType< ::foxbot::robot_SetComm > 
template<>
struct DataType< ::foxbot::robot_SetCommResponse>
{
  static const char* value()
  {
    return DataType< ::foxbot::robot_SetComm >::value();
  }
  static const char* value(const ::foxbot::robot_SetCommResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FOXBOT_MESSAGE_ROBOT_SETCOMM_H
