// Generated by gencpp from file foxbot/robot_SetCartesianEuler.msg
// DO NOT EDIT!


#ifndef FOXBOT_MESSAGE_ROBOT_SETCARTESIANEULER_H
#define FOXBOT_MESSAGE_ROBOT_SETCARTESIANEULER_H

#include <ros/service_traits.h>


#include <foxbot/robot_SetCartesianEulerRequest.h>
#include <foxbot/robot_SetCartesianEulerResponse.h>


namespace foxbot
{

struct robot_SetCartesianEuler
{

typedef robot_SetCartesianEulerRequest Request;
typedef robot_SetCartesianEulerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_SetCartesianEuler
} // namespace foxbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::foxbot::robot_SetCartesianEuler > {
  static const char* value()
  {
    return "627d7911ebf3dfc4900d0c03e6d07100";
  }

  static const char* value(const ::foxbot::robot_SetCartesianEuler&) { return value(); }
};

template<>
struct DataType< ::foxbot::robot_SetCartesianEuler > {
  static const char* value()
  {
    return "foxbot/robot_SetCartesianEuler";
  }

  static const char* value(const ::foxbot::robot_SetCartesianEuler&) { return value(); }
};


// service_traits::MD5Sum< ::foxbot::robot_SetCartesianEulerRequest> should match 
// service_traits::MD5Sum< ::foxbot::robot_SetCartesianEuler > 
template<>
struct MD5Sum< ::foxbot::robot_SetCartesianEulerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::foxbot::robot_SetCartesianEuler >::value();
  }
  static const char* value(const ::foxbot::robot_SetCartesianEulerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::foxbot::robot_SetCartesianEulerRequest> should match 
// service_traits::DataType< ::foxbot::robot_SetCartesianEuler > 
template<>
struct DataType< ::foxbot::robot_SetCartesianEulerRequest>
{
  static const char* value()
  {
    return DataType< ::foxbot::robot_SetCartesianEuler >::value();
  }
  static const char* value(const ::foxbot::robot_SetCartesianEulerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::foxbot::robot_SetCartesianEulerResponse> should match 
// service_traits::MD5Sum< ::foxbot::robot_SetCartesianEuler > 
template<>
struct MD5Sum< ::foxbot::robot_SetCartesianEulerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::foxbot::robot_SetCartesianEuler >::value();
  }
  static const char* value(const ::foxbot::robot_SetCartesianEulerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::foxbot::robot_SetCartesianEulerResponse> should match 
// service_traits::DataType< ::foxbot::robot_SetCartesianEuler > 
template<>
struct DataType< ::foxbot::robot_SetCartesianEulerResponse>
{
  static const char* value()
  {
    return DataType< ::foxbot::robot_SetCartesianEuler >::value();
  }
  static const char* value(const ::foxbot::robot_SetCartesianEulerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FOXBOT_MESSAGE_ROBOT_SETCARTESIANEULER_H
