// Generated by gencpp from file foxbot/robot_SetTrackDistRequest.msg
// DO NOT EDIT!


#ifndef FOXBOT_MESSAGE_ROBOT_SETTRACKDISTREQUEST_H
#define FOXBOT_MESSAGE_ROBOT_SETTRACKDISTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace foxbot
{
template <class ContainerAllocator>
struct robot_SetTrackDistRequest_
{
  typedef robot_SetTrackDistRequest_<ContainerAllocator> Type;

  robot_SetTrackDistRequest_()
    : pos_dist(0.0)
    , ang_dist(0.0)  {
    }
  robot_SetTrackDistRequest_(const ContainerAllocator& _alloc)
    : pos_dist(0.0)
    , ang_dist(0.0)  {
  (void)_alloc;
    }



   typedef double _pos_dist_type;
  _pos_dist_type pos_dist;

   typedef double _ang_dist_type;
  _ang_dist_type ang_dist;




  typedef boost::shared_ptr< ::foxbot::robot_SetTrackDistRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::foxbot::robot_SetTrackDistRequest_<ContainerAllocator> const> ConstPtr;

}; // struct robot_SetTrackDistRequest_

typedef ::foxbot::robot_SetTrackDistRequest_<std::allocator<void> > robot_SetTrackDistRequest;

typedef boost::shared_ptr< ::foxbot::robot_SetTrackDistRequest > robot_SetTrackDistRequestPtr;
typedef boost::shared_ptr< ::foxbot::robot_SetTrackDistRequest const> robot_SetTrackDistRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::foxbot::robot_SetTrackDistRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::foxbot::robot_SetTrackDistRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace foxbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'foxbot': ['/home/biomed/feroze_biorobotics/feroze_ws/src/foxbot/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::foxbot::robot_SetTrackDistRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::foxbot::robot_SetTrackDistRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::foxbot::robot_SetTrackDistRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::foxbot::robot_SetTrackDistRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::foxbot::robot_SetTrackDistRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::foxbot::robot_SetTrackDistRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::foxbot::robot_SetTrackDistRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "83ebed908297f9c3e07ef540f9857ab1";
  }

  static const char* value(const ::foxbot::robot_SetTrackDistRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x83ebed908297f9c3ULL;
  static const uint64_t static_value2 = 0xe07ef540f9857ab1ULL;
};

template<class ContainerAllocator>
struct DataType< ::foxbot::robot_SetTrackDistRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "foxbot/robot_SetTrackDistRequest";
  }

  static const char* value(const ::foxbot::robot_SetTrackDistRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::foxbot::robot_SetTrackDistRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
float64 pos_dist\n\
float64 ang_dist\n\
";
  }

  static const char* value(const ::foxbot::robot_SetTrackDistRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::foxbot::robot_SetTrackDistRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos_dist);
      stream.next(m.ang_dist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_SetTrackDistRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::foxbot::robot_SetTrackDistRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::foxbot::robot_SetTrackDistRequest_<ContainerAllocator>& v)
  {
    s << indent << "pos_dist: ";
    Printer<double>::stream(s, indent + "  ", v.pos_dist);
    s << indent << "ang_dist: ";
    Printer<double>::stream(s, indent + "  ", v.ang_dist);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FOXBOT_MESSAGE_ROBOT_SETTRACKDISTREQUEST_H
