// Generated by gencpp from file foxbot/robot_GetCartesianRequest.msg
// DO NOT EDIT!


#ifndef FOXBOT_MESSAGE_ROBOT_GETCARTESIANREQUEST_H
#define FOXBOT_MESSAGE_ROBOT_GETCARTESIANREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace foxbot
{
template <class ContainerAllocator>
struct robot_GetCartesianRequest_
{
  typedef robot_GetCartesianRequest_<ContainerAllocator> Type;

  robot_GetCartesianRequest_()
    : frameId(0)  {
    }
  robot_GetCartesianRequest_(const ContainerAllocator& _alloc)
    : frameId(0)  {
  (void)_alloc;
    }



   typedef uint8_t _frameId_type;
  _frameId_type frameId;




  typedef boost::shared_ptr< ::foxbot::robot_GetCartesianRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::foxbot::robot_GetCartesianRequest_<ContainerAllocator> const> ConstPtr;

}; // struct robot_GetCartesianRequest_

typedef ::foxbot::robot_GetCartesianRequest_<std::allocator<void> > robot_GetCartesianRequest;

typedef boost::shared_ptr< ::foxbot::robot_GetCartesianRequest > robot_GetCartesianRequestPtr;
typedef boost::shared_ptr< ::foxbot::robot_GetCartesianRequest const> robot_GetCartesianRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::foxbot::robot_GetCartesianRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::foxbot::robot_GetCartesianRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace foxbot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'foxbot': ['/home/biomed/feroze_biorobotics/feroze_ws/src/foxbot/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::foxbot::robot_GetCartesianRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::foxbot::robot_GetCartesianRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::foxbot::robot_GetCartesianRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::foxbot::robot_GetCartesianRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::foxbot::robot_GetCartesianRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::foxbot::robot_GetCartesianRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::foxbot::robot_GetCartesianRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0608ebf4f8d0e5c272f764313fb88e3e";
  }

  static const char* value(const ::foxbot::robot_GetCartesianRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0608ebf4f8d0e5c2ULL;
  static const uint64_t static_value2 = 0x72f764313fb88e3eULL;
};

template<class ContainerAllocator>
struct DataType< ::foxbot::robot_GetCartesianRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "foxbot/robot_GetCartesianRequest";
  }

  static const char* value(const ::foxbot::robot_GetCartesianRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::foxbot::robot_GetCartesianRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
uint8 frameId\n\
";
  }

  static const char* value(const ::foxbot::robot_GetCartesianRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::foxbot::robot_GetCartesianRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.frameId);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_GetCartesianRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::foxbot::robot_GetCartesianRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::foxbot::robot_GetCartesianRequest_<ContainerAllocator>& v)
  {
    s << indent << "frameId: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.frameId);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FOXBOT_MESSAGE_ROBOT_GETCARTESIANREQUEST_H
