// Generated by gencpp from file foxbot/robot_SpecialCommand.msg
// DO NOT EDIT!


#ifndef FOXBOT_MESSAGE_ROBOT_SPECIALCOMMAND_H
#define FOXBOT_MESSAGE_ROBOT_SPECIALCOMMAND_H

#include <ros/service_traits.h>


#include <foxbot/robot_SpecialCommandRequest.h>
#include <foxbot/robot_SpecialCommandResponse.h>


namespace foxbot
{

struct robot_SpecialCommand
{

typedef robot_SpecialCommandRequest Request;
typedef robot_SpecialCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_SpecialCommand
} // namespace foxbot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::foxbot::robot_SpecialCommand > {
  static const char* value()
  {
    return "dd470c01f667d001d212037b2fe2c918";
  }

  static const char* value(const ::foxbot::robot_SpecialCommand&) { return value(); }
};

template<>
struct DataType< ::foxbot::robot_SpecialCommand > {
  static const char* value()
  {
    return "foxbot/robot_SpecialCommand";
  }

  static const char* value(const ::foxbot::robot_SpecialCommand&) { return value(); }
};


// service_traits::MD5Sum< ::foxbot::robot_SpecialCommandRequest> should match 
// service_traits::MD5Sum< ::foxbot::robot_SpecialCommand > 
template<>
struct MD5Sum< ::foxbot::robot_SpecialCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::foxbot::robot_SpecialCommand >::value();
  }
  static const char* value(const ::foxbot::robot_SpecialCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::foxbot::robot_SpecialCommandRequest> should match 
// service_traits::DataType< ::foxbot::robot_SpecialCommand > 
template<>
struct DataType< ::foxbot::robot_SpecialCommandRequest>
{
  static const char* value()
  {
    return DataType< ::foxbot::robot_SpecialCommand >::value();
  }
  static const char* value(const ::foxbot::robot_SpecialCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::foxbot::robot_SpecialCommandResponse> should match 
// service_traits::MD5Sum< ::foxbot::robot_SpecialCommand > 
template<>
struct MD5Sum< ::foxbot::robot_SpecialCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::foxbot::robot_SpecialCommand >::value();
  }
  static const char* value(const ::foxbot::robot_SpecialCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::foxbot::robot_SpecialCommandResponse> should match 
// service_traits::DataType< ::foxbot::robot_SpecialCommand > 
template<>
struct DataType< ::foxbot::robot_SpecialCommandResponse>
{
  static const char* value()
  {
    return DataType< ::foxbot::robot_SpecialCommand >::value();
  }
  static const char* value(const ::foxbot::robot_SpecialCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FOXBOT_MESSAGE_ROBOT_SPECIALCOMMAND_H
